import time,os
while True:
    time.sleep(1)
    os.system('cls')
    print('Loading Please Wait')    
    time.sleep(1)
    os.system('cls')
    print('Loading Please Wait.')    
    time.sleep(1)
    os.system('cls')
    print('Loading Please Wait..')   
    time.sleep(1)
    os.system('cls')
    print('Loading Please Wait...')   
    time.sleep(1)
    os.system('cls')
    print('Loading Please Wait....')   